### ISSUE TITLE
Resolving new nodes for resoluition stuck at 66%

### ISSUE THREAD

**Issue by rollerjunge** [AccentuSoft/LinkScope_Client#13]
Hi, I'm new to linkscope, found it at reddit and I'm just trrying out wether its a serious competition for maltego. Therefore sorry for incorrect wording.

Whenever i use a resolution (?) , new nodes will be created. All new nodes appear on the same spot. Shortly after, usually when i distribute them menually on the graph window, the shown dialogue appears. It takes some minutes until it disappears.

i use the current portable version of Linkscope (downloaded it yesterday) on Windows 11.
![2022-03-05 14_25_28-Greenshot](https://user-images.githubusercontent.com/34043908/156885080-6bb3ca0a-4edf-4d12-a075-0499091f008d.png)

**Comment by rollerjunge** [comment]
Applies only to the portable version.

**Comment by AccentuSoft** [comment]
In the error message shown, it says that 'neato' is not found in path.

Did you install Graphviz, and is it in your path?

Edit to clarify: Graphviz is the library responsible for re-arranging the nodes on the canvases. It is required in order for the software to work.

**Comment by rollerjunge** [comment]
No. It is now as i used the installer for windows. Can be closed, error in OSI layer 8.
