### ISSUE TITLE
we need a version for debian kali / parrot os 

### ISSUE THREAD

**Issue by CodexTech0X** [AccentuSoft/LinkScope_Client#22]
we need a version for debian kali / parrot os thanks

**Comment by AccentuSoft** [comment]
This has already been requested; the Kali team is on it.
https://bugs.kali.org/view.php?id=8074

Installing the software through the installer should work for those platforms (as well as most other Debian flavors).

**Comment by CodexTech0X** [comment]
tested don't work in debian kali and parrot os and tested in ubuntu also problem install in windows many restriction

**Comment by AccentuSoft** [comment]
Could you let us know what specific problem you are having?
We re-tested the installer in a fresh Ubuntu 22.04 image and it worked as expected.

Note that we are referring to the graphical installer, the shell script is the old way of installing it and it is not supported. We just have it included in the repository for posterity. Also note that the compiled builds for LinkScope in this repository are for Ubuntu 22.04 and Windows 11. If you want to install the software on a different OS, you might need to either recompile it, or fiddle with it to make it work.

For the current Debian unstable (and possibly Kali and Parrot), you may need to delete libnssutil3.so from the program folder for LinkScope to work.

Could you please give us more details about the platform that you are trying to install the software on and the errors that you get?
