### ISSUE TITLE
Linkscope not opening (windows 11)

### ISSUE THREAD

**Issue by Miafenee** [AccentuSoft/LinkScope_Client#24]
I ran the offical installer and it installed everything. But when i tried to run linkscope it doesn't do anything, it didn't even gave me an error it just straight up didn't do anything.
Also when I search for it in the start menu it's not there.
Please help!

**Comment by AccentuSoft** [comment]
Hello,

Could you please verify that LinkScope was installed properly?
Does LinkScope.exe exist in your system? Check under 'Program Files' to see if the LinkScope directory was created.

**Comment by Miafenee** [comment]
It does

**Comment by AccentuSoft** [comment]
It might be that some libraries are missing; we have re-packed the 1.5.1 release to include all the libraries you should need. Please uninstall & reinstall LinkScope, and let us know if it works.

**Comment by Miafenee** [comment]
It works.
Thank you very much!

**Comment by Miafenee** [comment]
Sorry for reopening but I have another question. I downloaded the release and I can run the exe file in there, but how do I install it?

**Comment by AccentuSoft** [comment]
You should run the official installer to install it. If you already have another version installed, you should use the installer to uninstall the previous version. If you have downloaded and uncompressed the 7z file, you can also drag and drop the 'LinkScope' folder into 'C:\Program Files' to overwrite the previous version, if you have already installed LinkScope.

For ease of running the software, we recommend creating a Desktop Shortcut as part of the installation process.

**Comment by AccentuSoft** [comment]
Has this issue been resolved? @Miafenee
