### ISSUE TITLE
Missing DLLs on Windows

### ISSUE THREAD

**Issue by certrik** [AccentuSoft/LinkScope_Client#25]
```
ERROR: Resolution Website Information/Get External Urls failed during run: Host system is missing dependencies!

Full list of missing libraries:
    chrome_elf.dll
```

**Comment by AccentuSoft** [comment]
Hello,

Do you have chrome / chromium installed on your computer and in your PATH?

**Comment by certrik** [comment]
Yes. I do have` C:\Program Files\Google\Chrome\Application\114.0.5735.199\` in my %PATH%.
I know even copied the dll in the root of LinkScope.
Same error.

**Comment by AccentuSoft** [comment]
We've updated the Windows release for 1.5.1 to include a bunch of dlls. Please re-install, or uncompress the .7z file in Program Files, overwriting the previous LinkScope folder, and let us know if it works for you.

**Comment by certrik** [comment]
I am already on the 1.5.1 archive from GitHub.

**Comment by AccentuSoft** [comment]
Have you re-downloaded the release after our comment? We have not made a new release, just updated the existing one.

**Comment by certrik** [comment]
Thank you didn't get that. This works now. THX.
