### ISSUE TITLE
Modules not loading

### ISSUE THREAD

**Issue by icbestCA** [AccentuSoft/LinkScope_Client#29]
After adding a new source for modules, I can’t open the modules manager and the module is not doing anything not even appearing in the entities list. On Windows. I tried with the modules on this page: https://github.com/AccentuSoft/LinkScope-Module-Packs

**Comment by AccentuSoft** [comment]
Hello, could you please expand on the problem description?

Please include the following information:
- Windows version
- LinkScope version
- LinkScope log file
- Screenshots / Video of what you're trying to do and what you see

As a note, you should not need to add https://github.com/AccentuSoft/LinkScope-Module-Packs as a source, it should be already included by default. On the first startup, it might take some time for the module environment to be properly set up.

**Comment by icbestCA** [comment]
I'm on windows 11, 23H2 - 22631.3007
LinkScope is in version v1.6.0
Here is a the logs for trying loading the AccentuSoft LinkScope-Module-Packs Aleph, which have new entities and resolutions.
{Untitled} [2024-02-12 09:14:38,637] - INFO: Starting LinkScope Client, Version v1.6.0
{Untitled} [2024-02-12 09:14:38,674] - INFO: Loaded Local Entities Database.
{Untitled} [2024-02-12 09:14:38,947] - INFO: Project Untitled opened.
{Untitled} [2024-02-12 09:14:39,564] - INFO: Configured Modules environment. Loading Modules...
{Untitled} [2024-02-12 09:14:39,576] - INFO: Copied source files.
{Untitled} [2024-02-12 09:14:39,641] - INFO: Module environment upgrade status: Failed
{Untitled} [2024-02-12 09:14:39,641] - INFO: Modules Loaded.
{Untitled} [2024-02-12 09:15:09,767] - INFO: Database Saved.
{Untitled} [2024-02-12 09:15:09,788] - INFO: Project Saved

https://github.com/AccentuSoft/LinkScope_Client/assets/122579014/eb0c9b76-4597-45e3-9628-11ca6b265faa
Here is a video of me trying to load the module.
Thanks for your help.

**Comment by AccentuSoft** [comment]
It does not look like you are using the source 'https://github.com/AccentuSoft/LinkScope-Module-Packs'.
The source you show on the video shows a path to the local drive.

Does the structure of the folder match the structure described in the LinkScope-Module-Packs repository? Cloning the repository as-is and adding the path to its containing folder should work.

**Comment by AccentuSoft** [comment]
Has this issue been resolved?

**Comment by icbestCA** [comment]
Yeah, now i see the modules, but whenever I try to install one i get this error:  

Error occurred while installing Module Pack "Interpol Red and Yellow Notices":

Command ""C:\Users\me\AppData\Roaming\AccentuSoft\LinkScope

Client\User Module Packs Storage\Scripts\python.exe" -m pip install --upgrade

-r "C:\Users\me\AppData\Roaming\AccentuSoft\LinkScope Client\User

Module Packs Storage\requirements.txt.tmp'' returned non-zero exit status 1.

**Comment by AccentuSoft** [comment]
That looks to be an issue with your local environment, not the software itself.

Please email support with your support ID, and we will help you get back up and running.
If you do not have a support ID, you can get one here: https://accentusoft.com/pricing/
