### ISSUE TITLE
Cannot find installed playwright browsers.

### ISSUE THREAD

**Issue by kamupki** [AccentuSoft/LinkScope_Client#30]
any idea why "Cannot find installed playwright browsers." happened i already install the playwright but it keep telling me that way.
do i install the playwright wrong? any guide how to setup this thing

**Comment by AccentuSoft** [comment]
Hello, for installation/deployment issues, please email support with your support ID, and we will help you get set up.

If you do not have a support ID, you can get one here: https://accentusoft.com/pricing/
