### ISSUE TITLE
Flase Positive Trojan Status?

### ISSUE THREAD

**Issue by czeos** [AccentuSoft/LinkScope_Client#34]
Hi, I tried to download the LinkScope Client. 
I got an alert about a possible Win64/GenKryptik.GZEL trojan for UpdaterUtil.exe. I am using Eset ver 18.0.12.0

I found that the Eset made some false positive results for this type of trojan about 2 years ago.

**Comment by AccentuSoft** [comment]
Hello,

That is a false positive that comes up due to how the software updates itself. Since the software downloads the new version and unpacks it, as some malware do, this behavior is mistakenly classified as malicious, because we do not currently sign the binary with a certificate.
