### ISSUE TITLE
Missing LinkScope.bin when building from source

### ISSUE THREAD

**Issue by czeos** [AccentuSoft/LinkScope_Client#35]
Hi, 
I tried to build an application from the source by following the steps of your manual. After instaling the dependencies i started build.sh resulting in this error 
```
mv: cannot stat 'LinkScope/LinkScope.bin': No such file or directory
build.sh: 50: deactivate: not found
```
even though the file according to log was created
`Nuitka: Successfully created 'LinkScope.dist/LinkScope.bin'.` 

I was running this on ParrotOS 6.0 AMD64, and installed python 3.11.2

**Comment by AccentuSoft** [comment]
Hello,

Could you please provide more information? We would need the output of the build script, and the directory listing of the folder in which you ran the build script, both before and after execution.

From what you've posted, compilation seems to have succeeded in some way, so you should be able to run `LinkScope.bin` from within `LinkScope.dist` - do you see the file and the folder?
