### ISSUE TITLE
Feature Request: Add Dockbar Options to the View Menu

### ISSUE THREAD

**Issue by OSINT-Musings** [AccentuSoft/LinkScope_Client#5]
Right clicking on the the toolbar at the top of the application window to select which Dockbars to view is not intuitive and it took me quite a while to figure out how to get my Dockbars back. :P Perhaps moving those options to the view menu would be optimal?

Also, when I do right click the resulting menu interface it doesn't interactively highlight each option as I hover my mouse over it, as compared to the regular menu where the sub-menus do. 
![Nexus-current_situation-no-highlight](https://user-images.githubusercontent.com/94326094/141710064-0c74148f-db5f-4671-a746-cabc8ce8e8a5.png)
![Nexus-current_situation-highlight png](https://user-images.githubusercontent.com/94326094/141710066-2a031396-aaa5-46c7-991c-00542cb04c10.png)

**Comment by AccentuSoft** [comment]
Implemented in latest update: View -> Toggle visibility
